### PR TITLE
Feature/ui5 onboarding

### PR DESCRIPTION
**Pull request by mlucascardoso**
# Overview 
This branch contains: 
- UI5 onboarding data.
- HANA onboarding data.

### UI5 onboarding

1. Run docker-compose up
2. Open [UI5 onboarding](http://localhost:4000/2021/03/02/hana-onboarding/)
3. Check if the content is nice for new VAEES players

### HANA onboarding

1. Run docker-compose up
2. Open [HANA onboarding](http://localhost:4000/2021/03/01/ui5-onboarding/)
3. Check if the content is nice for new VAEES players

## Test Data 
N/A

### CODE REVIEW

**Review by edetec — COMMENTED** [review]
Good job man!

What do you think about using the target property to open the external links in a new tab?
Example: `[link text](the link){:target="_blank"}`

**Review by edetec — COMMENTED** [review]
I also recommend adding these: 

- Step 13: Margins and Paddings
- Step 31: Routing and Navigation
- Step 32: Routing with Parameters

**Comment by mlucascardoso** [comment]
> Good job man!
> 
> What do you think about using the target property to open the external links in a new tab?
> Example: `[link text](the link){:target="_blank"}`

Good idea, I'm gonna edit it today at night

**Comment by mlucascardoso** [comment]
> I also recommend adding these:
> 
> * Step 13: Margins and Paddings
> * Step 31: Routing and Navigation
> * Step 32: Routing with Parameters

What do you think to put the step 31 as mandatory and both 13 and 32 as suggestion?

Because we don't use these topics really often... At least I don't xD

**Pull request closed without merging**
